apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: grapejs
          image: nginx_box
          ports:
            - name: http-port
              containerPort: 80
          imagePullPolicy: Never
